#!/usr/bin/env ruby

# If we're loading from source instead of a gem, rubygems
# isn't setting load paths for us, so we need to set it ourselves
self_load_path = File.expand_path('../lib', File.dirname(__FILE__))
$LOAD_PATH << self_load_path unless $LOAD_PATH.include? self_load_path

require 'ncmc_authorities'

result = NCMCAuthorities::CommandLine.start(ARGV)
